### PR TITLE
simplify threads and drop @hook.singlethreaded

### PR DESCRIPTION
**Pull request by imnotjames**
this makes it so all commands have their own thread, instead of spawning
endless threads that spin up and die.  This means a simplification of logic
when dealing with creating plugins and how they interact with the rest of
the bot.  this should benefit us because the bot isn't doing any sort of
management of a thread pool.

### CODE REVIEW

**Comment by imnotjames** [comment]
I'm not sure I understand.

The previous implementation spawned a new thread for every single request that came in _unless_ `@hook.singlethreaded` was used.  This caused database locks and simultaneous writes to the same file to happen inadvertently (while, at the same time, not significantly improving performance).

What this does is that it simplifies the threading by essentially applying `@hook.singlethreaded` to every plugin - essentially setting up a thread pool management system, where a single thread is assigned to each plugin.

This protects us from a poorly written plugin from taking up a huge amount of stack space, as well - plugins which take long to respond can be abused by requesting the command multiple times to add a new thread to the stack.

Does this address your concern?

**Comment by Red-M** [comment]
Have you tested this across multiple IRC servers and triggering the plugin from all IRC servers?

**Comment by imnotjames** [comment]
That's a good point!  I've checked in the following cases:

* Multiple IRC servers with the same nick.
* The Same IRC server with a different nick but different channels.
* The Same IRC with a different nick but the same channel.

I think there could be performance issues if you were to have a VERY VERY high-throughput bot - eg some commands for a slow plugin would be queued behind that same plugin's commands.  However, I think this is preferable over running the bot out of stack space / memory.

**Comment by Red-M** [comment]
Also, I feel the amount of stack memory is fine here. I think you'd trigger anti spam from the IRC server before you'd blow the bot up. We can also just raise the stack memory amount.

**Comment by imnotjames** [comment]
Yes, I have tested against exceptions in plugins.  This catches them just like it always has.

**Comment by Red-M** [comment]
So any failure will cause that plugin to be unusable from that point onwards?

**Comment by imnotjames** [comment]
No, the original behavior for `@hook.singlethreaded` is to catch the exception, emit a trace, and continue execution skipping the command.

This is, essentially, the same action taken as the other code path, where a new thread is spawned for every response.

**Comment by Red-M** [comment]
I'd double check that since I remember that it leaves the plugin no longer able to run.

**Comment by imnotjames** [comment]
I had tested it with the following dummy plugin:

```
import random
from util import hook

@hook.command
def error(inp):
    if random.choice([ True, False ]):
        raise ValueError('error')
    return 'no error'
```

This causes the following output to emit:

```
>>> u'PRIVMSG #bot-testing :edward: woah'
Traceback (most recent call last):
03:15:16 #bot-testing <edward> .error
  File "core/main.py", line 117, in start
    self.run(self.func, input)
  File "core/main.py", line 96, in run
    out = func(input.inp)
  File "plugins/error.py", line 7, in error
    raise ValueError('woah')
ValueError: woah
03:15:17>>> u'PRIVMSG #bot-testing :edward: woah'
 #bot-testing <edward> .error
03:15:18 #bot-testing <edward> .error
Traceback (most recent call last):
  File "core/main.py", line 117, in start
    self.run(self.func, input)
  File "core/main.py", line 96, in run
    out = func(input.inp)
  File "plugins/error.py", line 7, in error
    raise ValueError('woah')
ValueError: woah
03:15:18 #bot-testing <edward> .error
>>> u'PRIVMSG #bot-testing :edward: woah'
Traceback (most recent call last):
  File "core/main.py", line 117, in start
    self.run(self.func, input)
  File "core/main.py", line 96, in run
    out = func(input.inp)
  File "plugins/error.py", line 7, in error
    raise ValueError('woah')
ValueError: woah
03:15:20 #bot-testing <edward> .error
>>> u'PRIVMSG #bot-testing :edward: woah'
```

**Comment by imnotjames** [comment]
I thought about it a bit.  I can see a case where there will be a problem - it's also currently a problem.. 

During reload, we delete the thread from the thread pool when the plug-in is unloaded, then reassign it when it's loaded back up with the new version.

Instead, we should swap it out, and then clean up the old thread.  This is because the processing could be continuing and adding new messages onto the queue for the plug-in at that name.  When we delete it, we'll get the python equivalent of a null pointer exception.

A further improvement from the current implementation may also be to transfer the queue over to another handler so the new code takes effect right away on queued up jobs.

**Comment by imnotjames** [comment]
Started using the higher level threading API, and I found that there MAYBE would be some edge case where a reload could theoretically have a period of time where we would dispatch against a function but then remove the thread for that function before the input could be applied.

**Comment by rmmh** [comment]
I don't think this simplifies the code more than it hinders it with new potential race conditions. Only a few plugins actually use singlethread, and especially for slow APIs (like WolframAlpha), having the concurrent requests is worth it.

I think we should circle back to this once we're on Python 3 and potentially use concurrent.futures to reimplement the singlethread behavior.

**Comment by imnotjames** [comment]
Hmm.. okay, I'm fine with that. However, I'm curious - what new race conditions does it introduce?

Right now, every command has a new thread spun up for it which accesses all the globals, and then the command thread dies as soon as that completes.  With that, you end up with an unlimited number of threads (except bound by stack).

**Pull request closed without merging**
