### PR TITLE
Support both Python3 and Python2

### PR DESCRIPTION
**Pull request by imnotjames**
This uses a bit of the python `future` tool, along
with hand-editing to get skybot to run on both Python2.7
as well as Python3.

* strings are unicode by default
* `print` is now a function rather than a language construct
* `Queue` is now queue
* the `U` flag for `open` is deprecated and emits a warning when used
* exceptions now use `Exception as e` notation rather than `Exception, e`
* to get values dict you now use `.values` rather than `.itervalues`
* to get items from dict you now use `.items` rather than `.iteritems`
* most interactions with sockets are in bytes unless specified otherwise
* `thread` is now in the `_thread` module
* function code is now under `.__code__` instead of `func_code`
* `urllib2` modules have been renamed and moved all over
* division has changed so we need ot use past old_div and __future__ division

# Manual Regression Testing

There is no real unit testing in place to ensure things keep working, I'm going to be doing some manual testing.

- [x] bf.py
- [x] bitcoin.py
- [x] cdecl.py
- [x] choose.py
- [x] crowdcontrol.py
- [x] crypto.py
- [x] dice.py
- [x] dictionary.py
- [x] dotnetpad.py
- [x] down.py
- [x] drama.py
- [x] gcalc.py
- [x] gif.py
- [x] google.py
- [x] hackernews.py
- [x] hash.py
- [x] help.py
- [x] imdb.py
- [x] lastfm.py
- [x] log.py
- [x] mem.py
- [x] metacritic.py
- [x] misc.py
- [ ] ~~mtg.py~~ [unrelated breakage](https://github.com/rmmh/skybot/pull/178)
- [x] pre.py
- [x] profile.py
- [x] pyexec.py
- [x] quote.py
- [x] religion.py
- [x] remember.py
- [x] rottentomatoes.py
- [x] seen.py
- [x] sieve.py
- [ ] ~~snopes.py~~ [unrelated breakage](https://github.com/rmmh/skybot/pull/179)
- [x] somethingawful.py
- [x] stock.py
- [x] suggest.py
- [x] tag.py
- [x] tell.py
- [x] tinyurl.py
- [ ] ~~translate.py~~ [unrelated breakage](https://github.com/rmmh/skybot/pull/197)
- [x] tvdb.py
- [x] twitter.py
- [x] urlhistory.py
- [x] validate.py
- [x] vimeo.py
- [x] weather.py
- [x] wikipedia.py
- [x] wolframalpha.py
- [x] youtube.py

# To Do before Ready

- [x] Regression Testing
- [x] Set up tox for testing across Python 2 / Python 3
- [x] Travis-CI?

### CODE REVIEW

**Comment by imnotjames** [comment]
If we want to use Travis CI for automated testing, that can be done with [tox-travis](https://github.com/tox-dev/tox-travis)

**Comment by rmmh** [comment]
Thanks for all the work! I think #185 is the only item left?

**Comment by rmmh** [comment]
I'm ok with *only* supporting Python 3, if it makes this PR simpler.

**Comment by imnotjames** [comment]
It would not change all that much.  Mostly, it'd drop the future dependency and a handful of lines using that.  Otherwise, python 2.7/3.0 don't have all that many hard differences.

**Comment by elitan** [comment]
Nice job. Time to merge!

**Comment by sklnd** [comment]
LGTM, very exciting

**Comment by rmmh** [comment]
Thanks for all the work! I just merged this with a minor fix for the cdecl test.

**Pull request merged**
