### PR TITLE
added API V3 support to youtube

### PR DESCRIPTION
**Pull request by Ell**
This requires a valid API Key from google apis console. Slap it in your config 

config {
    "youtube": { "key" KEY }
}

### CODE REVIEW

**Comment by olslash** [comment]
fine work :+1:

**Comment by rmmh** [comment]
can you make this take the 'google' api key and squash the commits?

**Comment by Ell** [comment]
merge this sucker in nerd

**Comment by rmmh** [comment]
thanks!

**Comment by tomjakubowski** [comment]
https://www.youtube.com/watch?v=0GidDVaM9xY

**Pull request closed without merging**
