### PR TITLE
Delete oblique.py

### PR DESCRIPTION
**Pull request by voronoipotato**
It's bad and worthless. Most of the commands are broken.

### CODE REVIEW

**Comment by Red-M** [comment]
I disagree

**Comment by voronoipotato** [comment]
What do you use it for? nobody uses oblique. it doesn't even work.

**Comment by Red-M** [comment]
I don't think you have any such visibility to claim that
>nobody uses oblique
and while I have not used this IRC bot in a while I am fairly certain
that Ryan would not push incomplete code to skybot.
Also a claim that just because no one uses it on your bot doesn't mean
its not used elsewhere.

**Comment by voronoipotato** [comment]
Clearly you don't use it otherwise you'd know why I made such a claim.

**Comment by voronoipotato** [comment]
It's so broken I literally thought you were an old friend messing with me. I thought clearly nobody actually uses this broken garbage that points to a bunch of unmaintained urls, but here we are. Someone who does not use it, defending its usage despite the fact that by and large it does not work.

**Comment by rmmh** [comment]
In the 6 years it's been active, I haven't found any legitimate uses.

**Pull request merged**
